from __future__ import annotations

import os
from pathlib import Path


DEFAULT_DB_PATH = Path(".agent") / "agent_memory.sqlite3"
DEFAULT_HANDOFFS_DIR = Path(".agent") / "handoffs"
DEFAULT_PATCH_RUNS_DIR = Path(".agent") / "patch_runs"
DEFAULT_PATCH_GIT_BRANCH_PREFIX = "codex/patch-run"
DEFAULT_PILOT_POLICY_PATH = Path(".agent") / "pilot_policy.toml"
DEFAULT_PILOT_TRACE_DIR = Path(".agent") / "pilot_traces"
DEFAULT_RECENT_EVENT_COUNT = 4
DEFAULT_MEMORY_LIMIT = 5
PILOT_DEFAULT_ACTION_LIMIT = 5
RECENCY_HALF_LIFE_DAYS = 21.0
CONTRADICTION_SCAN_EVENT_THRESHOLD = 1
REFLECTION_EVENT_THRESHOLD = 1
REFLECTION_MEMORY_THRESHOLD = 2
PROFILE_REFLECTION_THRESHOLD = 1
TASK_REVIEW_EVENT_THRESHOLD = 1
TASK_STALE_DAYS = 7.0
TASK_BLOCKED_STALE_DAYS = 3.0
TASK_NUDGE_COOLDOWN_HOURS = 24.0
TASK_ESCALATION_NUDGE_COUNT = 1
SHELL_COMMAND_TIMEOUT_SECONDS = 60.0
SHELL_OUTPUT_CHAR_LIMIT = 1200
FILE_OPERATION_PREVIEW_CHAR_LIMIT = 1200
PATCH_RUNNER_OUTPUT_CHAR_LIMIT = 20000
DEFAULT_OLLAMA_BASE_URL = os.getenv("MEMORY_AGENT_OLLAMA_BASE_URL", "http://127.0.0.1:11434")
DEFAULT_EMBED_MODEL = os.getenv("MEMORY_AGENT_EMBED_MODEL", "").strip()
DEFAULT_CHAT_MODEL = os.getenv("MEMORY_AGENT_CHAT_MODEL", "").strip()
MODEL_REQUEST_TIMEOUT_SECONDS = float(os.getenv("MEMORY_AGENT_MODEL_TIMEOUT_SECONDS", "45"))
DEFAULT_MODEL_KEEP_ALIVE = os.getenv("MEMORY_AGENT_MODEL_KEEP_ALIVE", "5m").strip()
SEMANTIC_RERANK_CANDIDATE_LIMIT = 12
SEMANTIC_RERANK_WEIGHT = 0.18
